### ISSUE TITLE
Add filtering on repository listing

### ISSUE THREAD

**Issue by ymartin59** [JFrogDev/nexus2artifactory#14]
We have many pages of repositories in listing and it would help to have some kind of filtering feature.
For instance in repository setup, a "f" command may ask for a word wich is then used to limit view in size, only showing matching repository names.

**Comment by DarthFennec** [comment]
Thanks for reaching out! We are aware of the usability issues with managing large lists of items in the UI, and we agree that some kind of filtering option is definitely necessary. This feature is planned for the next release or so, but I'll let you know.

**Comment by DarthFennec** [comment]
We've just pushed a massive update to support migration of Nexus 3, along with a number of other improvements, one of which is a filter feature. Let me know if this helps. Thanks!

**Comment by peters95** [comment]
Closing this issue due to age.
