### ISSUE TITLE
Feature Request / Question

### ISSUE THREAD

**Issue by chhex** [JFrogDev/nexus2artifactory#18]
Is it also possible to migration "only" the Security and the Repository Definitions, without migrating the actual Artifacts. So effectively the Artifactory Repo would be initially empty in terms of Artifacts, but would have the "same" user , groups and repository definitions.

**Comment by DarthFennec** [comment]
It is currently not possible to migrate local repositories without also migrating their artifacts. I can look into adding this feature if you would find it useful.

**Comment by chhex** [comment]
That would be terrific.  The idea is to start with a "clean" repo, but which is "compatible" in terms of repo and user definitions. And then populate the repo "newly" through Jenkins Builds. Does that make sense?

**Comment by chhex** [comment]
@DarthFennec we actually did'nt need the feature. We just did'nt migrate the repo and configured that one manually. So from my point of view we can close this request. 
BTW : The Migration went smooth, no problems. Thanks for the great Tool.

**Comment by DarthFennec** [comment]
Ah, alright, that works. I'm glad the tool ran smoothly for you!
