### ISSUE TITLE
Migrator is throwing error : Configuration file security.xml is not valid. 

### ISSUE THREAD

**Issue by shivakumarreddy78** [JFrogDev/nexus2artifactory#19]
Hi JFrogDev team,

I am working on migrating user, repositories and all the data inside repositories from nexus 2.x to Artifactory.

I am getting an error in the initial setup screen of the migrator. The error is Configuration file security.xml is not valid. 

I am running this on RHEL and python version 2.6.6.

I verified the nexus path and found the security.xml file is a valid file inside config folder inside Nexus Data Directory.

---
Initial Setup 														
n: Nexus Data Directory ! /opt/mount1/casfw/nexus2.x/sonatype-work/nexus/      
                   															
a: Artifactory URL !                                                           
u: Artifactory Username !                                                      
p: Artifactory Password !                                                      
                   															
h: Help            															
q: Back            															

**Configuration file security.xml is not valid.**            
                      
---

can you please help me fix this issue and migrate from Nexus to Artifactory

**Comment by DarthFennec** [comment]
Hi, thank you for opening an issue.

Try running the tool again, and pass the options `--log-level debug --log-file logfile.txt`. This will write debug logs to a new `logfile.txt` file, which should contain more information about exactly what the tool is tripping up on.

**Comment by shivakumarreddy78** [comment]
Thanks for your quick response. Yes, I ran the code with log option and below is the out put of the log where i can see the error related to initial setup.

_2018-04-04 00:54:49,142 [MainThread] [DEBUG] (nex2art.core.Screen:138) - Key 'ENTER' pressed.
2018-04-04 00:54:49,145 [MainThread] [INFO] (nex2art.core.Nexus2:28) - Reading Nexus config from /opt/mount1/casfw/nexus2.x/sonatype-work/nexus/conf/nexus.xml.
2018-04-04 00:54:49,170 [MainThread] [INFO] (nex2art.core.Nexus2:58) - Successfully read Nexus config.
2018-04-04 00:54:49,170 [MainThread] [INFO] (nex2art.core.Ldap2:17) - Reading LDAP config from /opt/mount1/casfw/nexus2.x/sonatype-work/nexus/conf/ldap.xml.
2018-04-04 00:54:49,170 [MainThread] [INFO] (nex2art.core.Ldap2:24) - LDAP config file does not exist, skipping.
2018-04-04 00:54:49,171 [MainThread] [INFO] (nex2art.core.Security2:21) - Reading security config from /opt/mount1/casfw/nexus2.x/sonatype-work/nexus/conf/security.xml.
2018-04-04 00:54:49,584 [MainThread] [ERROR] (nex2art.core.Security2:49) - Error reading security config:
Traceback (most recent call last):
  File "/home/casfw/migrator/nex2art/core/Security2.py", line 32, in refresh
    nprivs, nprivmap = self.getprivileges(xml, targs)
  File "/home/casfw/migrator/nex2art/core/Security2.py", line 202, in getprivileges
    privtmp[propxml.find('key').text] = propxml.find('value').text
AttributeError: 'NoneType' object has no attribute 'text'
2018-04-04 00:54:49,585 [MainThread] [INFO] (nex2art.core.Format:124) - Updating data tree with Nexus data.
2018-04-04 00:54:49,586 [MainThread] [INFO] (nex2art.core.Validate:24) - Validating tree from '/Initial Setup/Nexus Data Directory'._

can you please look in to the and suggest how to fix it and proceed ?

**Comment by DarthFennec** [comment]
Judging from the log output, it appears that a property of one of your privileges is missing either a `<key>` or a `<value>` section, but the migrator expects both to exist. I can update the code to be more lenient in this situation, but first I'd like to understand why Nexus views this as valid, and how it interprets the lack of field here (this would allow me to fix the issue more correctly). If it's not too much trouble, could you try to find which `<property>` section is missing either a `<key>` or a `<value>` section? If possible, it would be great if you could provide the entire `<privilege>` block the property belongs to. Thanks.

**Comment by shivakumarreddy78** [comment]
Yes, you are correct. I see that in the security.xml file, under priviledges there are some property tags that are missing the value section. This is in our DEVELOPMENT server.

Now, i ran the same in TEST environment and found below error in the log file.

> 2018-04-05 06:51:20,155 [MainThread] [DEBUG] (nex2art.core.Screen:138) - Key 'ENTER' pressed.
> 2018-04-05 06:51:20,292 [MainThread] [INFO] (nex2art.core.Nexus2:28) - Reading Nexus config from /opt/webhost/data/sonatype-work/nexus/conf/nexus.xml.
> 2018-04-05 06:51:20,431 [MainThread] [INFO] (nex2art.core.Nexus2:58) - Successfully read Nexus config.
> 2018-04-05 06:51:20,432 [MainThread] [INFO] (nex2art.core.Ldap2:17) - Reading LDAP config from /opt/webhost/data/sonatype-work/nexus/conf/ldap.xml.
> 2018-04-05 06:51:20,444 [MainThread] [INFO] (nex2art.core.Ldap2:21) - Successfully read LDAP config.
> 2018-04-05 06:51:20,445 [MainThread] [INFO] (nex2art.core.Security2:21) - Reading security config from /opt/webhost/data/sonatype-work/nexus/conf/security.xml.
> 2018-04-05 06:51:20,976 [MainThread] [ERROR] (nex2art.core.Security2:49) - Error reading security config:
> Traceback (most recent call last):
>   File "/home/cda/nexus2artifactory/nex2art/core/Security2.py", line 35, in refresh
>     self.flattentargets(privs)
>   File "/home/cda/nexus2artifactory/nex2art/core/Security2.py", line 81, in flattentargets
>     targ = priv['target']
> KeyError: 'target'
> 2018-04-05 06:51:20,998 [MainThread] [INFO] (nex2art.core.Format:124) - Updating data tree with Nexus data.
> 2018-04-05 06:51:20,999 [MainThread] [INFO] (nex2art.core.Validate:24) - Validating tree from '/Initial Setup/Nexus Data Directory'.
> 2018-04-05 06:51:29,740 [MainThread] [DEBUG] (nex2art.core.Screen:138) - Key 'q' pressed.
> 2018-04-05 06:51:29,746 [MainThread] [INFO] (nex2art.core.Validate:24) - Validating tree from '/'.
> 2018-04-05 06:51:29,750 [MainThread] [INFO] (nex2art.core.Validate:24) - Validating tree from '/Initial Setup'.
> 2018-04-05 06:51:30,776 [MainThread] [DEBUG] (nex2art.core.Screen:138) - Key 'q' pressed.
> 2018-04-05 06:51:33,903 [MainThread] [DEBUG] (nex2art.core.Screen:138) - Key 'y' pressed.
> 2018-04-05 06:51:33,909 [MainThread] [INFO] (root:33) - Terminating Nexus migration tool.

can you help fix this error for us ?
we want to try the migrator first in NON-PRO environment before we actually use it in PRODUCTION environment.

**Comment by DarthFennec** [comment]
You appear to have a privilege which uses a repository target that doesn't exist. Can you confirm?

**Comment by mmercer-apixio** [comment]
@DarthFennec My speculation is that this occurs when someone has migrated from nxrm2 to nxrm3 (as was our case).  I can replicate the issue on my end.  Fortunately, it at least tells me what it finds, but it will likely still need to be a lot of cleanup to be able to migrate from an nxrm3 (migrated from nxrm2) environment.

``2018-04-13 19:47:47,607 [MainThread] [ERROR] (nex2art.core.Security3:95) - Error reading security config:
Traceback (most recent call last):
  File "/root/nexus2artifactory/nex2art/core/Security3.py", line 73, in refresh
    roledata = self.getrole(role, privmap)
  File "/root/nexus2artifactory/nex2art/core/Security3.py", line 134, in getrole
    for priv in role['privileges']: privs.append(privmap[priv])
KeyError: u'nx-repository-view-maven2-central-browse'
``

**Comment by DarthFennec** [comment]
@mmercer-apixio Are you sure you're talking about the same issue? It looks like shivakumarreddy78 is migrating from Nexus 2 directly to Artifactory, so what you're talking about seems unrelated to me.

Although, this does seem to potentially explain some of the other issues I've been seeing lately. If Sonatype's 2-to-3 migration allows these hanging privileges to persist into Nexus 3 somehow, it would certainly cause errors like this when trying to migrate to Artifactory. As for how the bad privileges get into Nexus 2 in the first place, it seems likely that users would edit the XML files by hand, and might make mistakes while doing so.

**Comment by mmercer-apixio** [comment]
@DarthFennec i was only speculating that the cause was the migration.  in our case, it appears to be at minimally very similar, we are getting the 'error reading security config' and I saw the comment here and grabbed the log.  In his case, it's the target, in ours, its the roles, but they both seem to arise from the same origination of being unable to parse the original security tree.  unfortunately with nxrm3, i believe most of this is stored in the db, not in a flat file?  so it may be harder to trace it for nxrm3?  I can open a separate ticket, as I said, i arrived here from the same 'origin'  the error reading security config

**Comment by DarthFennec** [comment]
That's true, it is effectively the same error. I just mean that the two errors may not be caused by the same underlying issue. You seemed to be speculating that his error (in Nexus 2) was due to the same cause as yours (the migration to Nexus 3), which of course couldn't be the case. So I was a little confused. But now I understand where you're coming from.

I was looking at a similar issue earlier today, on a new (not migrated) Nexus 3 instance. There were users with nonexistent roles. I think that one is also unrelated, and has something to do with the way Nexus 3 deals with LDAP, but I'm not entirely certain.

You're right, Nexus 3 stores all of this data in the database. I use a [simple groovy script](https://github.com/JFrogDev/nexus2artifactory/blob/master/nex2art/resources/plugin.groovy) to extract all the data for the migrator to use, and I'm pretty certain it shouldn't be missing or forgetting anything, so the output from that should reflect what you would find in the database. I expect if you [ran the script](https://help.sonatype.com/repomanager3/rest-and-integration-api/script-api), you'd find a group with a permission `nx-repository-view-maven2-central-browse`, but no permission entry of that name (and probably no `maven2-central` repository).

**Comment by mmercer-apixio** [comment]
I will look into this and get back to you on it this weekend.  Thanks for the link to the script :)

**Comment by DarthFennec** [comment]
@mmercer-apixio I think I fixed your issue (context: issue #25). Let me know if it works for you. Thanks!

**Comment by peters95** [comment]
closing this issue due to age.
