### ISSUE TITLE
repository migration mkopt <-/-> does not appear to work

### ISSUE THREAD

**Issue by sellers** [JFrogDev/nexus2artifactory#23]
Core.py menu options for pagination do not appear to respond to input on Ubuntu 14.04 over SSH.  The input is ignored.

**Comment by DarthFennec** [comment]
Odd ... Does it respond to those inputs if you're editing in a text field? What about if you're in the remote shell, or in a different program over ssh? What about your local shell?

I'd expect curses to know how to interpret those keypresses properly. I'd also expect ssh, your remote shell, your terminal, etc to handle it correctly, but clearly something's going wrong at some point in the chain.

Depending on what the problem ends up being, it might make sense to bind an alternate set of keys to those inputs.

**Comment by peters95** [comment]
closing issue due to age
