### ISSUE TITLE
Repository migration with subset of artifacts

### ISSUE THREAD

**Issue by gavinbunney** [JFrogDev/nexus2artifactory#30]
We have a mostly-mono releases repository setup in Nexus. In the brave-new-Artifactory world, we are planning on splitting this up into smaller repositories.

Is it possible to migrate a repository based on a content selector (in nexus terminology)? i.e. pull all the artifacts from the `releases` repository, but only select the `com.comany.product-a/**/*` artifacts?

This would allow us to do a piecemeal migration, only pulling across a subset of artifacts from a repository into artifactory at a time.

Thanks!

**Comment by DarthFennec** [comment]
This isn't possible currently. I like the idea though. Might think about adding this in the future.

I think the correct approach at the moment is to create more repositories and move the appropriate artifacts to them in Nexus, and then migrate.

**Comment by gavinbunney** [comment]
Thanks - nexus isn't great about moving such a large amount of artifacts around unfortunately :( We'll look at other options though; cheers
