### ISSUE TITLE
I get something wrong in SuSElinux,this platform is not supported by UniCurses

### ISSUE THREAD

**Issue by lzwzzy** [JFrogDev/nexus2artifactory#33]
Here is the outputs of those commands:
![image](https://user-images.githubusercontent.com/23731957/46990552-681c7480-d134-11e8-8ae6-2b0f96864af1.png)

**Comment by DarthFennec** [comment]
The `curses` Python library is standard, and should generally come with Python. However, some systems might split the package, and I'm pretty sure SuSE is one of those. Try installing the `python-curses` package, then it should work.

**Comment by peters95** [comment]
Closing this issue due to age
