### ISSUE TITLE
Add summary output even for less verbose options

### ISSUE THREAD

**Issue by patbat95008** [JFrogDev/nexus2artifactory#34]
Some users need the Nexus2Artifactory script to run quickly without much output, but need the summary to validate the migration was successful.

The "info" log level can slow the script as it has to print each event to the log file.

The script should print out a summary to the standard output or log file even if the -v warn or -v error log level is specified.

**Comment by DarthFennec** [comment]
Changed the log level of the summary to `CRITICAL`, so it will show up even if you set the log filter to a high level.
