### ISSUE TITLE
Error reading repository config

### ISSUE THREAD

**Issue by schefs** [JFrogDev/nexus2artifactory#36]
We have Nexus 3 installed as a container. The data directory where blobs cache DB etc ... Is mounted to the same server the container run on. 
When running the nexus2art and passing the mount path as Nexus directory I get this error :
"Error reading repository config"
We tried everything with no results ... 
We tried to run nexus2art inside the container but got error in screen.py
When it tries to create border saying int does not have attribute border in universes.py line 854
Thanks in advance

**Comment by DarthFennec** [comment]
Thanks for opening an issue. Could you provide a full stacktrace, or the logs from the tool? If you run the tool with the options `-v debug -l debug.log`, it will write logs that you can share. That should provide more information as to what's wrong.

**Comment by schefs** [comment]
Hey, thanks for the reply, the problem was that I used -s argument and the Nexus didn't like it, so I removed few lines in Nexus3.py and it solved that.

**Comment by DarthFennec** [comment]
Glad you fixed it. For reference, which lines did you remove?

**Comment by schefs** [comment]
instead of:
```
if self.scr.sslnoverify:
                ctx = ssl.create_default_context()
                ctx.check_hostname = False
                ctx.verify_mode = ssl.CERT_NONE
                resp = urllib2.urlopen(req, context=ctx)
            else: resp = urllib2.urlopen(req)
            stat = resp.getcode()
```
just use:

```
resp = urllib2.urlopen(req)
            stat = resp.getcode()
```
my nexsus is using https same as my artifactory, i used -s arg and for some reason it just said that the nexus has problems with the ssl so i just removed the ssl usage inside Nexus.py - "dorequest" function

**Comment by DarthFennec** [comment]
I see, so you're effectively using `-s` for Artifactory connections but not for Nexus connections. I didn't realize disabling SSL verification could prevent a connection from working.

Perhaps it makes sense to have two separate options for this, instead of one?
