### ISSUE TITLE
ImportError 

### ISSUE THREAD

**Issue by Bkumar87** [JFrogDev/nexus2artifactory#39]
I downloaded NexustoArtifactory tool on the instance where Nexus is installed, but im unable to run ./NexustoArtifactory.py.  Getting issue while importing argparse. Please help me resolve this issue.  Thanks. 

![image](https://user-images.githubusercontent.com/49071695/57645968-855fd700-758d-11e9-95dc-9e8e8b1fb8d2.png)

**Comment by DarthFennec** [comment]
`argparse` is standard, so it should already be installed as part of Python. Although, it's possible that some systems will package some standard Python libraries separately, in which case you have to install the extra packages. What OS/distro are you using?

**Comment by Bkumar87** [comment]
We are using OS 6.5

**Comment by DarthFennec** [comment]
I'm not sure what you mean. I'm asking about your operating system. Is the instance where Nexus is installed running Windows, MacOS, Debian, RHEL, CentOS, or something else?

**Comment by Bkumar87** [comment]
i am running RHEL 6.5 os version.  and the python that is installed is 2. 6.6.

**Comment by DarthFennec** [comment]
I see, thank you. Looks like `argparse` wasn't standard until Python 2.7, so that explains why you don't have it. You can install it using `easy_install argparse`, or `pip install argparse`.

**Comment by peters95** [comment]
closing issue due to age
