### ISSUE TITLE
nexus2artifactory is not able to access artifactory url

### ISSUE THREAD

**Issue by sow1234** [JFrogDev/nexus2artifactory#4]
We are trying to migrate data from Nexus to Artifactory using nexus2artifactory tool. We are blocked in the first step itself, in the initial setup menu, while giving the artifactory url, we got the below error:

Unable to access artifactory url. and errors in lines 435,548,473,407,556
HTTP Error 503 : Service unavailable

Artifactory url is accessible in browser and running successfully. But the tool is not able to recognize artifactory. Please let us know if anything  needs to be configured for the tool to connect to artifactory.

**Comment by sellers** [comment]
Please ensure that you use the full URI for your artifactory.  That may be something to the effect of https://artifactory.url/artifactory/  

This resolved an issue I had with connectivity (the panel was red and turned green once I had the URI, username, and password correct).

**Comment by peters95** [comment]
Closing issue due to age
