### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by kb7791** [JFrogDev/nexus2artifactory#49]
Hi @DarthFennec ,

Quick question about Run the migration". During the migration process certain artifacts might errors during the transfer. Ids there any logging that might give me some detail on what artifacts had errors and why?

**Comment by DarthFennec** [comment]
There is logging, but you have to enable it. As detailed in the [readme](https://github.com/jfrog/nexus2artifactory/blob/master/README.md#options), you can enable logging by passing the following options:

```
./NexusToArtifactory.py -v debug -l logfile.log
```

This example will log everything to a file `logfile.log`.

**Comment by kb7791** [comment]
Thanks DarthFennec
