### ISSUE TITLE
Pip and Conan migration issue

### ISSUE THREAD

**Issue by kb7791** [JFrogDev/nexus2artifactory#50]
So migrating pip and conan repos we are hosting from Nexus 3 to Artifactory seems to get botched in a way that even after making the appropriate changes to index urls to locations of these packages. 

When running a test build against the new index urls for these packages that were moved over I end up getting 404 errors.

` HTTP error 404 while getting http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/packages/pip/19.2.3/pip-19.2.3-py2.py3-none-any.whl#md5=22874c2949cbaac15a778176c2f0f546 (from http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*)
  Could not install requirement pip from http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/packages/pip/19.2.3/pip-19.2.3-py2.py3-none-any.whl#md5=22874c2949cbaac15a778176c2f0f546 because of error 404 Client Error: Not Found for url: http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/packages/pip/19.2.3/pip-19.2.3-py2.py3-none-any.whl
Could not install requirement pip from http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/packages/pip/19.2.3/pip-19.2.3-py2.py3-none-any.whl#md5=22874c2949cbaac15a778176c2f0f546 because of HTTP error 404 Client Error: Not Found for url: http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/packages/pip/19.2.3/pip-19.2.3-py2.py3-none-any.whl for URL http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/packages/pip/19.2.3/pip-19.2.3-py2.py3-none-any.whl#md5=22874c2949cbaac15a778176c2f0f546 (from http://10.1.1.113:8081/artifactory/api/pypi/pypi-all/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*)
"$PYTHON_MOD pip install -q --index-url $PIP_URL --trusted-host $PIP_IP --upgrade pip" command failed with exit code 1.`

**Comment by gislifreyr** [comment]
There seems to be some issue with the path that the packages are put in Artifactory. They are put under the `packages/` folder and the api seems to return that path for download. However the files are actually kept in the root folder of the repo so the download link you receive is of the wrong path.

To fix this in your Artifactory setup you could move all the packages manually in the UI from the packages directory and into the root folder. That is what I did and it worked fine. I presume this could be done via the API but I couldn't be bothered to have a look at that since I only had about 20 projects.

**Comment by kb7791** [comment]
> There seems to be some issue with the path that the packages are put in Artifactory. They are put under the `packages/` folder and the api seems to return that path for download. However the files are actually kept in the root folder of the repo so the download link you receive is of the wrong path.
> 
> To fix this in your Artifactory setup you could move all the packages manually in the UI from the packages directory and into the root folder. That is what I did and it worked fine. I presume this could be done via the API but I couldn't be bothered to have a look at that since I only had about 20 projects.

Yeah that what I ended up having to do was manually moving the pypi stuff out but had to create a local script to install the conan packages locally then upload using conan cmds to upload them into proper conan repo in Artifactory

**Comment by gislifreyr** [comment]
> Yeah that what I ended up having to do was manually moving the pypi stuff out but had to create a local script to install the conan packages locally then upload using conan cmds to upload them into proper conan repo in Artifactory

You might want to paste that script here, if you can, so others that have problems with migrating Conan can use it.
