### ISSUE TITLE
Run migration failed

### ISSUE THREAD

**Issue by blundercon** [JFrogDev/nexus2artifactory#68]
I am facing the exact same issue mentioned in https://github.com/jfrog/nexus2artifactory/issues/57. The migration fails with ```TypeError: string indices must be integers, not str```. Any ideas how to resolve this ?

**Comment by DarthFennec** [comment]
If it's the same stacktrace (not just the same error message) I can look at the linked issue to see what the problem might be. But if you can post your stacktrace or confirm that it's the same as the linked issue, that would be fantastic. If not, the error may or may not be coming from a different part of the codebase.

Assuming the stacktrace in the linked issue matches yours, it seems as though the tool is calling Artifactory's `api/repositories` endpoint, and getting back something unexpected, some kind of error perhaps. If you use curl to call the same endpoint from the same place, it may provide us more information about what's wrong:

```
curl -v -u username:password https://<host>:<port>/artifactory/api/repositories
```

**Comment by blundercon** [comment]
> 
> 
> If it's the same stacktrace (not just the same error message) I can look at the linked issue to see what the problem might be. But if you can post your stacktrace or confirm that it's the same as the linked issue, that would be fantastic. If not, the error may or may not be coming from a different part of the codebase.
> 
> Assuming the stacktrace in the linked issue matches yours, it seems as though the tool is calling Artifactory's `api/repositories` endpoint, and getting back something unexpected, some kind of error perhaps. If you use curl to call the same endpoint from the same place, it may provide us more information about what's wrong:
> 
> ```
> curl -v -u username:password https://<host>:<port>/artifactory/api/repositories
> ```

Seems like the issue here was just a confusing stacktrace. I ran the tool with more verbose logging and noticed that there were `HTTP 403` errors. The CLI seemed to have accepted the Artifactory UI URL without complaining instead of the API URL. Fixing that resolved the issue.
