### ISSUE TITLE
Broken execution since #6

### ISSUE THREAD

**Issue by zonArt** [JFrogDev/nexus2artifactory#8]
Hi,

It looks like that since #6 which was proposed by myself, the tool fails silently when migrating maven repository as no default `Maven Snapshot Version Behavior` is defined and tool needs one.

@DarthFennec: initially in my PR I proposed a value when user didn't set anything (to avoid editing all the repo he wants to migrate) and with your proposal to have a list of chosen value, this was lost making it mandatory to edit all the repos.

I'll propose something as soon as I got a minute

**Comment by DarthFennec** [comment]
Odd, I seem to have a default value of `unique` when I run it. In fact, you specified the default value [here](https://github.com/JFrogDev/nexus2artifactory/commit/064d8a395213cc03edb071ef776a407ad4bcc572#diff-d11cbf1ab2a9411b6b2f49f2e53eed5cR48), and I set it in the UI [here](https://github.com/JFrogDev/nexus2artifactory/commit/bd5519d9a3a132ec92966bff0d9fd8345f0f387b#diff-97c95323f457b146ba711a28e3add884R16). So by all means you should be seeing defaults, no?

**Comment by zonArt** [comment]
Mmmh looks like you're right, from a fresh setup it works as expected but not when loading an existing config
