### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by faenschi** [JFrogDev/nexus2artifactory#9]
Hi all

I'm not able to start the script on a windows machine:

$ ./NexusToArtifactory.py
Traceback (most recent call last):
  File "./NexusToArtifactory.py", line 4, in <module>
    import unicurses
  File "E:\apps\nexus2artifactory\unicurses.py", line 60, in <module>
    pdlib = ctypes.CDLL(pdcursesdll)   # we're on winXX, use pdcurses instead of native ncurses
  File "E:\apps\Python27\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

regards angela

**Comment by DarthFennec** [comment]
This tool uses the ncurses library, which is a standard python feature in Linux and MacOS, but not in Windows. To run the tool in Windows, as mentioned in the README file, the [pdcurses](https://pdcurses.sourceforge.io/) library must be present. There are a couple different builds of this library for different backends, but I think I would recommend the SDL version (`pdc34dlls.zip` on the download page, note that this build also requires the [SDL1.2](https://www.libsdl.org/download-1.2.php) library). Alternately, you can use the native Windows build (`pdc32dllw.zip` on the download page), which shouldn't require any other libraries, but I've had trouble with that one in the past, so I don't know how well it works. Once you have your `pdcurses.dll` and/or `SDL.dll` files, you should just be able to put them in the project directory and they'll be loaded when you run the tool.

I realize this can get a little complicated and is not very well documented, and I have attempted to streamline it in the past by building a standalone exe of the project, but the last time I was successful with that was with a very early version. If I can get that working, I'll put the exe in this repository. In any case, let me know if you have any questions or if pdcurses gives you trouble.
